Update several notebooks to use cleaner `odc-geo` code
GeoscienceAustralia/dea-notebooks pull request #1186
Opened 2024-02-15 03:57 UTC by robbibt

### Proposed changes
Include a brief description of the changes being proposed, and why they are necessary.

### Closes issues (optional)
- Closes Issue #000

### Checklist 
(Replace `[ ]` with `[x]` to check off)

- [ ] Notebook created using the [DEA-notebooks template](https://github.com/GeoscienceAustralia/dea-notebooks/tree/develop)
- [ ] Remove any unused Python packages from `Load packages`
- [ ] Remove any unused/empty code cells
- [ ] Remove any guidance cells (e.g. `General advice`)
- [ ] Ensure that all code cells follow the [PEP8 standard](https://www.python.org/dev/peps/pep-0008/) for code. The `jupyterlab_code_formatter` tool can be used to format code cells to a consistent style: select each code cell, then click `Edit` and then one of the `Apply X Formatter` options (`YAPF` or `Black` are recommended).
- [ ] Include relevant tags in the final notebook cell (refer to the [DEA Tags Index](https://docs.dea.ga.gov.au/genindex/), and re-use tags if possible)
- [ ] Clear all outputs, run notebook from start to finish, and save the notebook in the state where all cells have been sequentially evaluated
- [ ] Test notebook on both the `NCI` and `DEA Sandbox` (flag if not working as part of PR and ask for help to solve if needed)
- [ ] If applicable, update the `Notebook currently compatible with the NCI|DEA Sandbox environment only` line below the notebook title to reflect the environments the notebook is compatible with
- [ ] Check for any spelling mistakes using the DEA Sandbox's built-in spellchecker (double click on markdown cells then right-click on pink highlighted words). For example:

![sandbox_spellchecker](https://github.com/GeoscienceAustralia/dea-notebooks/assets/17680388/c5e5848b-fd54-4eb5-aae9-29838761f2af)

2024-02-19 23:59 UTC, BexDunn commented on How_to_guides/Analyse_multiple_polygons.ipynb
>     "cell_type": "markdown",
<p>Hi, these comments seem to be from the old notebook : &nbsp;&nbsp;</p><p> </p><p># Append results to a dictionary using the attribute</p><p>&nbsp;&nbsp;# column as an key</p><p>&nbsp;&nbsp;# results.update({str(row[attribute_col]): ds_masked})</p><p> </p><p>Suggest updating to reflect new usage?</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/GeoscienceAustralia/dea-notebooks/pull/1186/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='17'/>

2024-02-19 23:59 UTC, BexDunn commented on How_to_guides/Analyse_multiple_polygons.ipynb
>     "cell_type": "markdown",
<p>We're getting a runtime value here, and a quick search suggests that matplotlib is flagging us trying to cast a NaN to a colour in the colourmapping function (and not handling the error). Do you think that's correct? Is this something we should flag with matplotlib or some difference between odc.geo and datacube.utils in specifying number formats? </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/GeoscienceAustralia/dea-notebooks/pull/1186/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='24'/>

2024-02-20 00:02 UTC, BexDunn commented on How_to_guides/Analyse_multiple_polygons.ipynb
>     "cell_type": "markdown",
![image](https://github.com/GeoscienceAustralia/dea-notebooks/assets/20038594/4adf1806-1924-4c07-bd3c-24d631d5238d)

2024-02-20 00:03 UTC, BexDunn approved these changes
Looks great, and very useful. Two comments on the Analyse multiple polys notebook.
First, a couple of comments in the text to update: 
# Append results to a dictionary using the attribute
  # column as an key
  # results.update({str(row[attribute_col]): ds_masked})

And secondly, something funky happening with the error message on the plot related to casting numbers? - more details in the comments, and reviewNB

2024-02-20 00:04 UTC, BexDunn requested changes
argh, please see other review! I meant to request changes :)

2024-02-20 00:58 UTC, robbibt commented
Hey @BexDunn, I fixed up the comment - but when I re-ran the notebook, the runtime warning disappeared. I've had that happen before - it's a confusing! Can keep an eye out for it if it re-appears

2024-02-20 01:01 UTC, BexDunn approved these changes

2024-02-20 01:32 UTC, merged