Edited the repo's README
GeoscienceAustralia/dea-notebooks pull request #1193
Opened 2024-02-26 03:42 UTC by benji-glitsos-ga

### Proposed changes

Preview the README: <https://github.com/GeoscienceAustralia/dea-notebooks/tree/feature/update-repo-readme>

* Converted README from Restructured Text to Markdown format
* Edited entire README
* Moved the ‘Git workflow’ content out into a wiki article and linked to it: https://github.com/GeoscienceAustralia/dea-notebooks/wiki/Git-workflow
* Separated the ‘Introduction’ section into two sections: Browse the DEA Knowledge Hub and Use the DEA Sandbox
* Added more links to the DEA Sandbox than on the current README

I’ve spellchecked my work.

### Closes issues (optional)

- https://github.com/GeoscienceAustralia/dea-notebooks/issues/1167

### Checklist 
(Replace `[ ]` with `[x]` to check off)

- [ ] Notebook created using the [DEA-notebooks template](https://github.com/GeoscienceAustralia/dea-notebooks/tree/develop)
- [ ] Remove any unused Python packages from `Load packages`
- [ ] Remove any unused/empty code cells
- [ ] Remove any guidance cells (e.g. `General advice`)
- [ ] Ensure that all code cells follow the [PEP8 standard](https://www.python.org/dev/peps/pep-0008/) for code. The `jupyterlab_code_formatter` tool can be used to format code cells to a consistent style: select each code cell, then click `Edit` and then one of the `Apply X Formatter` options (`YAPF` or `Black` are recommended).
- [ ] Include relevant tags in the final notebook cell (refer to the [DEA Tags Index](https://docs.dea.ga.gov.au/genindex/), and re-use tags if possible)
- [ ] Clear all outputs, run notebook from start to finish, and save the notebook in the state where all cells have been sequentially evaluated
- [ ] Test notebook on both the `NCI` and `DEA Sandbox` (flag if not working as part of PR and ask for help to solve if needed)
- [ ] If applicable, update the `Notebook currently compatible with the NCI|DEA Sandbox environment only` line below the notebook title to reflect the environments the notebook is compatible with
- [ ] Check for any spelling mistakes using the DEA Sandbox's built-in spellchecker (double click on markdown cells then right-click on pink highlighted words). For example:

![sandbox_spellchecker](https://github.com/GeoscienceAustralia/dea-notebooks/assets/17680388/c5e5848b-fd54-4eb5-aae9-29838761f2af)

2024-02-26 04:23 UTC, robbibt requested changes

2024-02-26 04:23 UTC, robbibt commented on README.md
Hey @benji-glitsos-ga , this is looking great. A few comments:

1) Now that there is text above here, these lines get a bit visually lost for me. They are intended as a kind of "at a glance" info section - is there any way we can help differentiate them from the other content? E.g. put them in an alert box/change the font size/reduce spacing/bullet point them etc? Not exactly sure what would work best here.
![image](https://github.com/GeoscienceAustralia/dea-notebooks/assets/17680388/5d773160-901d-4d61-9b4e-aac13a56b630)

2) DEA Notebooks is intended to run on the NCI too. We probably need to mention this high up (e.g. "and used on the DEA Sandbox and National Computational Infrastructure (NCI)", and likely as a new section under "Use the DEA Sandbox" (pointing to the NCI user guides on Knowledge Hub)

2024-02-26 04:23 UTC, robbibt commented on README.md
> +[xarray](http://xarray.pydata.org/en/stable/). You can see real-world
"Real-world use cases" adds confusion about the "Real world examples" notebooks section. Maybe "You can view external use cases"?

2024-02-26 04:23 UTC, robbibt commented on README.md
> +how to use the tools and data to conduct a broad range of geospatial
```suggestion
how to use DEA data and tools to conduct a broad range of geospatial
```

2024-02-26 04:23 UTC, robbibt commented on README.md
> +  algorithms to assist in analysing DEA data.
Can we add a link to the rendered DEA Tools API docs here?

2024-02-26 04:23 UTC, robbibt commented on README.md
> +The **[DEA Sandbox](https://app.sandbox.dea.ga.gov.au/)** is a free virtual environment for interacting with the notebooks and tools. You can use the sandbox to conduct geospatial analysis without in
```suggestion
The **[DEA Sandbox](https://app.sandbox.dea.ga.gov.au/)** is a free virtual environment for interacting with the notebooks and tools from your internet browser. You can use the Sandbox to conduct geospatial analysis without installing anything on your computer.
```

2024-02-26 04:27 UTC, robbibt commented on README.md
> +  algorithms to assist in analysing DEA data.
Ignore this, it's already linked!

Although, perhaps we should instead use relative links here so they open up correctly on the Sandbox? Could always leave the DEA Tools one as it is.

2024-02-26 22:57 UTC, robbibt commented on README.md
> +[DEA Sandbox](https://app.sandbox.dea.ga.gov.au/) and the [National Computational Infrastructure (NCI)](https://nci.org.au/).
I think we should point to our own docs here, as there's not an easy path for users to get started on the NCI without our custom setup. I wouldn't be against pointing to our Sandbox docs here either, but it's less critical than for the NCI.

```suggestion
[DEA Sandbox](https://app.sandbox.dea.ga.gov.au/) and the [National Computational Infrastructure (NCI)](https://docs.dea.ga.gov.au/guides/setup/NCI/README/).
```

2024-02-26 22:57 UTC, robbibt commented on README.md
> +https://docs.dea.ga.gov.au/guides/setup/NCI/README/
Is this line accidental? The "NCI" link directly above points to the same place.

2024-02-26 22:58 UTC, robbibt commented on README.md
> +All notebooks in this repository contain tags describing
I wonder if we should leave this paragraph out completely - the tags functionality currently needs a lot of work, and might not be something we want to highlight so prominently.

2024-02-26 23:04 UTC, robbibt commented on README.md
> +The Knowledge Hub is where you can easily view the notebooks and read DEA Tools documentation. You can browse the following sections.
Hey @benji-glitsos-ga, thinking about this some more, I think we might want to change these sections up a little. The list of notebook folder dotpoints below applies more specifically to DEA Notebooks than Knowledge Hub itself - I would change the following:

1. Move the notebook folder dotpoints up under "Introduction" (and perhaps rename this folder"), and change their links to relative links that will open directly on the Sandbox and Github
2. Keep the "Browse the DEA Knowledge Hub, but update it to include a short paragraph describing the kind of content it provides - e.g. technical product metadata, DEA user and reference guides, changelog and tech alerts, DEA Tools Python API etc.

2024-02-27 01:53 UTC, benji-glitsos-ga commented on README.md
> +The Knowledge Hub is where you can easily view the notebooks and read DEA Tools documentation. You can browse the following sections.
It turns out the Sandbox doesn't render Markdown files so therefore, I think not many people will be opening these links from the sandbox. I've used absolute links because this README page will be used on the Knowledge Hub for the near future.

![ksnip_20240227-102642](https://github.com/GeoscienceAustralia/dea-notebooks/assets/144193171/bf52a6ad-f1ff-45d7-b3d9-955294a8b431)

2024-02-27 01:53 UTC, benji-glitsos-ga commented on README.md
(1) I moved the 2nd paragraph to an 'Introduction' section. Unfortunately, using formatting to 'showcase' that section is possible only using HTML which is harder for stakeholders to edit so I'd prefer sticking to plain markdown.
(2) Done

2024-02-27 02:19 UTC, robbibt commented on README.md
> +The DEA Knowledge Hub is where you can easily view the notebooks and read DEA Tools documentation. You can browse the following sections.
Either we bold this, or remove the bold from the bolded "DEA Sandbox" below:

```suggestion
The **DEA Knowledge Hub** is where you can easily view the notebooks and read DEA Tools documentation. You can browse the following sections.
```

2024-02-27 02:19 UTC, robbibt commented on README.md
> +## View on the Knowledge Hub
```suggestion
## View on the DEA Knowledge Hub
```

2024-02-27 02:20 UTC, robbibt approved these changes
Looks awesome, thanks for this @benji-glitsos-ga !

2024-02-27 02:24 UTC, merged