fix bug in SpatialKFold method of train-test-split
GeoscienceAustralia/dea-notebooks pull request #709
Opened 2020-11-12 00:13 UTC by cbur24

Also added a verbose flag to `spatial_clusters`

### Proposed changes
Quick edit to fix behaviour of the `SpatialKFold` method in SKCV and `spatial_train_test_split`.  Emphasizing the `n_splits` parameter to better satisfy the train-test ratio for this method ('SpatialShuffleSplit' method works as intended).

2020-11-30 23:39 UTC, MatthewJA requested changes
Got a few suggestions

2020-11-30 23:39 UTC, MatthewJA commented on Scripts/dea_classificationtools.py
> +    if verbose == True:
Just `if verbose`

2020-11-30 23:39 UTC, MatthewJA commented on Scripts/dea_classificationtools.py
> +    n_groups : int
It'd be nice if these parameter documentations were in the same order as they are in the function

2020-11-30 23:39 UTC, MatthewJA commented on Scripts/dea_classificationtools.py
> +                             test_size,
If you want to emphasise n_splits, consider making it non-optional, instead of making test_size non-optional.

2020-11-30 23:39 UTC, MatthewJA commented on Scripts/dea_classificationtools.py
> +        number to satisfy the train-test size ratio desired, as the 'test_size'
(and train_size)

2020-11-30 23:39 UTC, MatthewJA commented on Scripts/dea_classificationtools.py
>      if kfold_method == 'SpatialShuffleSplit':
Consider throwing a warning if you use train_size/test_size rather than n_splits, especially if you're considering fixing it in future

2020-12-01 01:32 UTC, cbur24 commented
Thanks @MatthewJA, made a bunch of changes reflecting your comments

2020-12-01 03:45 UTC, MatthewJA approved these changes
Nice! One minor complaint but all good to merge I reckon

2020-12-01 03:45 UTC, MatthewJA commented on Scripts/dea_classificationtools.py
> +    if dask == True:
Can also just use `if dask` here

2020-12-01 03:59 UTC, merged