Major update to remove Scripts, compatibility with new Sandbox image
GeoscienceAustralia/dea-notebooks pull request #865
Opened 2021-09-08 06:20 UTC by robbibt

### Proposed changes
This update:
* Removes the `Scripts` directory, and updates all notebooks to load directly from `dea-tools` using:
```
import sys
sys.path.insert(1, '../Tools/')
from dea_tools.datahandling import load_ard
```

* Updates the repository for compatibility with recent updates to the DEA Sandbox image which are currently implemented on the [dev Sandbox](https://sandbox.dev.dea.ga.gov.au/).

### Closes issues (optional)
- Closes #731
- Closes #849
- Closes #732

2021-09-08 23:50 UTC, MatthewJA commented
I'd like to fix the `__version__` hack - basically the version is still totally gettable we just need to use setuptools_scm to do it. This isn't a blocker on getting the PR merged though; I'm happy to have it merged and then do a separate PR for that. Just noting my intent!

2021-09-08 23:50 UTC, MatthewJA commented
(not a review, just a note)

2021-09-09 04:44 UTC, robbibt commented
@MatthewJA Can you quickly check this one? Still looks like an error in the middle: https://github.com/GeoscienceAustralia/dea-notebooks/blob/sep_update/Real_world_examples/Subpixel_waterbodies.ipynb (Cell 12)
![image](https://user-images.githubusercontent.com/17680388/132623950-7f1eca6a-c9fc-4ad8-82b0-eba289f09937.png)

2021-09-09 05:17 UTC, MatthewJA commented
whoops, I fix

2021-09-09 05:24 UTC, MatthewJA commented
Try now @robbibt

2021-09-09 22:47 UTC, MatthewJA requested changes
Got some minor requests.

2021-09-09 22:47 UTC, MatthewJA commented on Frequently_used_code/ARD_overpass_predictor.ipynb
> +    "from datetime import datetime, timedelta"
Is datetime used anywhere? I don't think it is, otherwise (as best I can tell) this would break.

2021-09-09 22:47 UTC, MatthewJA commented on Tools/dea_tools/__init__.py
> +except:
Should be `except ImportError`; no bare `except`s!

2021-09-09 23:34 UTC, robbibt commented
Thanks @MatthewJA - the `datetime` thing was fine (`datetime` is a submodule of `datetime` and it's used here: `today = datetime.today()`). I've fixed the try/except!

2021-09-09 23:56 UTC, MatthewJA approved these changes
LGTM

2021-09-09 23:58 UTC, merged