Forecasting/modelling notebook
GeoscienceAustralia/dea-notebooks pull request #911
Opened 2022-03-31 05:45 UTC by cbur24

### Proposed changes
Proposing to add a vegetation forecasting/modelling notebook to the `Real_world_examples` folder, ported over from DE Africa repo. 

In draft form until [this issue](https://github.com/GeoscienceAustralia/dea-sandbox/issues/217) is resolved

2023-01-09 03:27 UTC, robbibt commented
Hey @cbur24! Just checking on on this one - was this previously blocked by issues with the NCI environment?

2023-01-09 04:42 UTC, cbur24 commented
@robbibt This PR was in draft form as the Sandbox image needed to be updated due a conflict between `scipy` and `statsmodel`.
I've rerun the notebook and can confirm it works now.   I'll label it as ready-for-review and leave it up to DEA team to decide if its something they want in the repo.

2023-10-23 04:25 UTC, uchchwhash approved these changes
Looks good to me!

2023-10-23 06:34 UTC, robbibt requested changes
Hey @cbur24, sorry this has taken so long for us to progress! It's a really great notebook, and will be awesome to finally get it merged in.

Since the notebook was written, there's been a bunch of changes including Sentinel-2 products being renamed. I've checked out the branch and updated them to the new Collection 3.

The notebook was also pretty slow on the default Sandbox server, so I've updated the notebook to use only Sentinel-2A data, and a `min_gooddata` of 0.9. This means a lot less timesteps to load, but may potentially have changed the results - could you check the new outputs and make sure everything is as expected?

My only requested change is around the intro of the notebook: the "Background" section dives straight into pretty technical detail right up. I think adding in a sentence or two at the very beginning outlining the scientific/management case for forecasting using remote sensing data would make the notebook much more approachable to beginner users: essentially, outlining the case for why it's an important tool/case study. 🙂 

Apart from that, looks great to me!

2023-10-23 23:46 UTC, cbur24 commented
@uchchwhash @robbibt 
Thanks guys. I had a look at this notebook again last week during some down time which is why I pushed the re-merge with `develop`. I'll implement the changes requested next time I've got an hour or two free.

2023-11-22 23:49 UTC, robbibt commented
Hey @cbur24, would love to merge this - I'm happy to write up a sentence or two for the intro if you're busy - I just wanted to add a tiny bit extra to emphasise the importance/usefulness of the use case. 🙂

2025-04-02 21:56 UTC, cbur24 commented
@robbibt I have refined this notebook and I reckon its good-to-go.  I'm no longer across the procedures for getting notebooks merged (I've got no idea what tests are being run and why they fail), so when you have a minute please review and let me know what needs to be done.  

Relatedly, maybe one day in the future you can school me on all that's changed with DEA-Notebook procedures?

2025-07-24 23:19 UTC, jennaguffogg approved these changes

2025-07-24 23:19 UTC, jennaguffogg approved these changes

2025-07-24 23:20 UTC, merged